<?php

if (function_exists('acf_add_local_field_group')) :

	acf_add_local_field_group(array(
		'key' => 'group_5fd910bde4220',
		'title' => 'Banner de destaque',
		'fields' => array(
			array(
				'key' => 'field_5fd910da2c67d',
				'label' => 'Imagem de fundo',
				'name' => 'imagem',
				'type' => 'image',
				'instructions' => 'Insira a imagem de fundo do banner',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5fd911272c67e',
				'label' => 'Título',
				'name' => 'texto',
				'type' => 'text',
				'instructions' => 'Insira um texto ao banner',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5fd9114b2c67f',
				'label' => 'Texto (link)',
				'name' => 'texto_do_link',
				'type' => 'text',
				'instructions' => 'Se houver algum link, digite o texto que apontará para lá',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5fd911822c680',
				'label' => 'Url (link)',
				'name' => 'url_do_link',
				'type' => 'url',
				'instructions' => 'Se houver um link, digite a url dele',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5fd9114b2c67f',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'slider_banner',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5fd937ff41f15',
		'title' => 'Casas',
		'fields' => array(
			array(
				'key' => 'field_5fd93842c9143',
				'label' => 'Conteúdo 1',
				'name' => 'conteudo_1',
				'type' => 'wysiwyg',
				'instructions' => 'Insira o conteúdo da página',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5fd938a7c9144',
				'label' => 'Galeria de fotos',
				'name' => 'galeria_de_fotos',
				'type' => 'wysiwyg',
				'instructions' => 'Crie um título e uma galeria de fotos (não ponha legenda em nenhuma foto)',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5fd938d9c9145',
				'label' => 'Diferenciais',
				'name' => 'conteudo_2',
				'type' => 'wysiwyg',
				'instructions' => 'Crie um título e uma galeria de fotos com os diferenciais da casa. (Ponha legenda)',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5fd939dec9148',
				'label' => 'Conteúdo da chamada de destaque',
				'name' => 'conteudo_cta',
				'type' => 'wysiwyg',
				'instructions' => 'Crie um título e um botão com link para sua chamada de destaque',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5fd93a0dc9149',
				'label' => 'Imagem da chamada de destaque',
				'name' => 'img_cta',
				'type' => 'image',
				'instructions' => 'Insira uma imagem para a chamada de destaque',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5fd939dec9148',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'house',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'permalink',
			1 => 'the_content',
			2 => 'excerpt',
			3 => 'discussion',
			4 => 'comments',
			5 => 'revisions',
			6 => 'slug',
			7 => 'author',
			8 => 'format',
			9 => 'page_attributes',
			10 => 'featured_image',
			11 => 'categories',
			12 => 'tags',
			13 => 'send-trackbacks',
		),
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5fd9120abc0eb',
		'title' => 'Depoimentos',
		'fields' => array(
			array(
				'key' => 'field_5fd9121f9eda0',
				'label' => 'Imagem',
				'name' => 'imagem',
				'type' => 'image',
				'instructions' => 'Insira uma imagem da pessoa que estará fazendo o depoimento',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5fd9125c9eda1',
				'label' => 'Nome',
				'name' => 'nome',
				'type' => 'text',
				'instructions' => 'Insira o nome da pessoa que fará o depoimento',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5fd912789eda2',
				'label' => 'Conteúdo do depoimento',
				'name' => 'depoimento',
				'type' => 'textarea',
				'instructions' => 'Escreva o depoimento da pessoa aqui',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => 'wpautop',
			),
			array(
				'key' => 'field_5fd912ad9eda3',
				'label' => 'Link',
				'name' => 'link',
				'type' => 'url',
				'instructions' => 'Se houver algum vídeo desse depoimento, entre com o link aqui',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5fd912789eda2',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'depoimentos',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5fd911c40679b',
		'title' => 'Parceiros',
		'fields' => array(
			array(
				'key' => 'field_5fd911e21eb32',
				'label' => 'Logo',
				'name' => 'logo',
				'type' => 'image',
				'instructions' => 'Insira o logo do seu parceiro',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'slider_partners',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5fd93a7852f8c',
		'title' => 'Serviços',
		'fields' => array(
			array(
				'key' => 'field_5fd93a78cdfac',
				'label' => 'Conteúdo 1',
				'name' => 'conteudo_1',
				'type' => 'wysiwyg',
				'instructions' => 'Insira o conteúdo da página',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5fd93a78d1a41',
				'label' => 'Galeria de fotos',
				'name' => 'galeria_de_fotos',
				'type' => 'wysiwyg',
				'instructions' => 'Crie um título e uma galeria de fotos (não ponha legenda em nenhuma foto)',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5fd93bcfe71a9',
				'label' => 'Conteúdo 2',
				'name' => 'conteudo_2',
				'type' => 'wysiwyg',
				'instructions' => 'Insira o conteúdo da página que virá depois da galeria de fotos',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5fd93a78d1a41',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5fd93a78d8fa4',
				'label' => 'Conteúdo da chamada de destaque',
				'name' => 'conteudo_cta',
				'type' => 'wysiwyg',
				'instructions' => 'Crie um título e um botão com link para sua chamada de destaque',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5fd93a78dcad8',
				'label' => 'Imagem da chamada de destaque',
				'name' => 'img_cta',
				'type' => 'image',
				'instructions' => 'Insira uma imagem para a chamada de destaque',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5fd93a78d8fa4',
							'operator' => '!=empty',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'service',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5fd90f6590a04',
		'title' => 'Sobre a empresa',
		'fields' => array(
			array(
				'key' => 'field_5fd90f6b73549',
				'label' => 'Facebook',
				'name' => 'facebook',
				'type' => 'url',
				'instructions' => 'Insira o link do Facebook da empresa',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5fd90f9a7354a',
				'label' => 'Instagram',
				'name' => 'instagram',
				'type' => 'url',
				'instructions' => 'Insira o link do Instagram da empresa',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5fd90fb07354b',
				'label' => 'Linkedin',
				'name' => 'linkedin',
				'type' => 'url',
				'instructions' => 'Insira o link do Linkedin da empresa',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5fd90fc07354c',
				'label' => 'Whatsapp',
				'name' => 'whatsapp',
				'type' => 'text',
				'instructions' => 'Insira número de celular da empresa',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5fd910377354d',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'email',
				'instructions' => 'Insira o email da empresa',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5fd9104f7354e',
				'label' => 'Telefone',
				'name' => 'telefone',
				'type' => 'text',
				'instructions' => 'Insira o telefone da empresa',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5fd910917354f',
				'label' => 'Endereço',
				'name' => 'endereco',
				'type' => 'text',
				'instructions' => 'Insira o endereço da empresa',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'information',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

endif;
